POST http://localhost:8080/api/signup
content-type: application/json

{ "email": "phd9911@gmail.com", "password": "123456" }
######################
POST http://localhost:8080/api/signin
content-type: application/json

{ "email": "phd9911@gmail.com", "password": "123456" }
#######################
POST http://localhost:8080/api/resetpass
content-type: application/json

{ "email": "example@email.com" }
#######################
GET http://localhost:8080/api/notes